[package]
cairo-version = "2.12.2"
name = "full_starter_react"
version = "1.7.2"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --account-address $DEPLOYER_ACCOUNT_ADDRESS --private-key $DEPLOYER_PRIVATE_KEY --fee strk"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.2" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v1.6.1" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.2" }

# Ensure transitive dependencies from `achievement` use the same Dojo version
[patch.'https://github.com/dojoengine/dojo']
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.2" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.2" }

[profile.sepolia]
